### ISSUE TITLE
compiling a deb fails

### ISSUE THREAD

**Issue by A-nglea** [Trevelopment/MZD-AIO#64]
my run to compile this to a deb fails with:-

Step 5/5 : RUN cd /work     && npm install
 ---> Using cache
 ---> 5df8498c21d2
Successfully built 5df8498c21d2
Successfully tagged build-mzd-aio-lnx:latest
+ docker run -v /home/angela/MZD-AIO:/work -v /home/angela/MZD-AIO:/output -t build-mzd-aio-lnx /work/scripts/build_linux_deb_helper.sh
+ pushd ./work
/work /
+ npm run-script build:linux:x64

> MZD-AIO-TI@2.8.4 build:linux:x64 /work
> npm run prebuild && build --linux deb AppImage --x64 && npm run postbuild

> MZD-AIO-TI@2.8.4 prebuild /work
> node build/target.js

**Preparing Target: release
/work/node_modules/read-config-file/out/main.js:71
async function readConfig(configFile, request) {
      ^^^^^^^^**
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at _readConfigFile (/work/node_modules/electron-builder/src/cli/cli.ts:10:1)
    at Object.args [as handler] (/work/node_modules/electron-builder/src/cli/cli.ts:45:5)
    at Object.runCommand (/work/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/work/node_modules/yargs/yargs.js:1072:28)
    at Object.get [as argv] (/work/node_modules/yargs/yargs.js:1004:21)
    at Object.<anonymous> (/work/node_modules/electron-builder/src/cli/cli.ts:19:1)
    at Module._compile (module.js:577:32)

**Comment by A-nglea** [comment]
Re-pulled everything and it compiles after correcting package.json - there were a number of trailing commas before a block closures },  and the xml refused to parse.

My problem now is that it refuses to run. It complains the xml2js module is missing; it isn't.

**Comment by Trevelopment** [comment]
I am gong to push some fixed code in the next few days I am just fine tuning it.
